[theme]
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
maxUploadSize=10

[cli]
# THIS IS THE CRITICAL LINE: Forces Python 3.11 for installation and running
pythonVersion = "3.11"
